# Generated by Django 5.2.6 on 2025-09-25 06:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='tags',
        ),
        migrations.AddField(
            model_name='resume',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
