# Generated by Django 5.2.6 on 2025-09-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_tags_resume_uploaded_at_alter_resume_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
