# Generated by Django 5.2.6 on 2025-10-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_company_job_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='url',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skills',
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
