# Generated by Django 5.2.6 on 2025-10-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_rename_url_job_link_remove_job_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='link',
            field=models.URLField(blank=True, default='https://remoteok.com/', null=True),
        ),
    ]
