# Generated by Django 5.2.6 on 2025-10-04 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_job_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userjobview',
            options={},
        ),
    ]
